
- name: 'Discover Database {{ workload_tag }}{{ db_home_name }} Unique Name'
  when: db_unique_name is not defined
  delegate_to: localhost
  import_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: db_unique_name is defined }

- name: 'Discover Oracle Home'
  when: oracle_home is not defined
  delegate_to: localhost
  import_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'
- assert: { that: oracle_home is defined }

- name: 'Create PDB Using DBCA Silent Mode'
  shell:  |
    dbca -silent -createPluggableDatabase -sourceDB {{ db_unique_name }} -pdbName {{ PDBname }} -pdbAdminUserName pdbadmin -pdbAdminPassword {{ pdb_admin_password }} -createUserTableSpace true -pdbStorageMAXSizeInMB 100000
  become: 'true'
  become_user: 'oracle'
  become_method: 'sudo'
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    PATH: '{{ ansible_env.PATH }}:{{ oracle_home }}/bin'
  register: pdb_creation_result
  failed_when: pdb_creation_result.stdout.find('100% complete') == -1
- debug:
    msg: '{{ pdb_creation_result }}'

- name: 'Create Set TDE for PDB sql'
  copy:
    dest: '/tmp/SetTDEforPDB.sql'
    content: |
      ALTER SESSION SET CONTAINER = {{ PDBname }};
      ADMINISTER KEY MANAGEMENT SET KEY FORCE KEYSTORE IDENTIFIED BY "{{ db_wallet_password }}" WITH BACKUP;
      QUIT;
  become: 'true'
  become_user: oracle
  become_method: sudo
  register: create_tde_sql_result
- debug:
    msg: '{{ create_tde_sql_result }}'

- name: Set TDE Key for PDB
  shell: |
    {{ oracle_home }}/bin/sqlplus / as sysdba @/tmp/SetTDEforPDB.sql
  become: yes
  become_user: oracle
  become_method: sudo
  environment:
    ORACLE_HOME: '{{ oracle_home }}'
    ORACLE_SID: '{{ oracle_sid }}'
  register: set_tde_result
- debug:
    msg: '{{ set_tde_result }}'