
# Discover DB Home for Database

- name: 'Discover DB Home for Database {{ cdb_name | lower }}'
  when: db_home_id is not defined or compartment_id is not defined
  include_role:
    name: 'database_home'
    tasks_from: 'db_home_discovery.yml'
- name: 'Assert that db_home_id and compartment_id are defined'
  assert: { that: db_home_id is defined and compartment_id is defined }

# Discover Database 

- name: 'Discover Database {{ cdb_name | lower }}'
  oci_database_database_facts:
    compartment_id: '{{ compartment_id }}'
    db_home_id: '{{ db_home_id }}'
    db_name: '{{ cdb_name | lower }}'
  register: 'db_discovery_result'
- name: 'Database Discovery Output'
  debug:
    msg: '{{ db_discovery_result }}'
- set_fact: 
    database_id: '{{ db_discovery_result.databases[0].id }}'
    database_lifecycle_state: '{{ db_discovery_result.databases[0].lifecycle_state }}'
    db_unique_name: '{{ db_discovery_result.databases[0].db_unique_name }}'
  when: db_discovery_result.databases|length == 1 