
- name: 'Get OCID for {{ cdb_name | lower }} DB'
  when: database_id is not defined
  include_role:
    name: 'database'
    tasks_from: 'db_discovery.yml'
- assert: { that: database_id is defined }

- name: 'Enable automatic database backups'
  when: auto_backup_enabled == 'true'
  oci_database_database:
    database_id: '{{ database_id }}'
    db_backup_config:
      auto_backup_enabled: '{{ auto_backup_enabled }}'
      auto_backup_window: '{{ auto_backup_window }}'
      recovery_window_in_days: '{{ recovery_window_in_days }}'
  register: 'enable_auto_backup_result'
- debug:
    msg: '{{ enable_auto_backup_result }}'

- name: 'Disable automatic database backups'
  when: auto_backup_enabled == 'false'
  oci_database_database:
    database_id: '{{ database_id }}'
    db_backup_config:
      auto_backup_enabled: '{{ auto_backup_enabled }}'
  register: 'disable_auto_backup_result'
- debug:
    msg: '{{ disable_auto_backup_result }}'

