
- name: 'Check VM Cluster Lifecycle State'
  when: exadata_type is defined and (exadata_type == 'exacs' or exadata_type == 'exacc')
  include_tasks: '{{ exadata_type }}_vm_cluster_discovery.yml'

- name: 'Check that VM Cluster is available'
  assert:
    that: vm_cluster_lifecycle_state is defined and vm_cluster_lifecycle_state == 'AVAILABLE'
    fail_msg: 'VM Cluster was not found or was not in AVAILABLE state. Please run playbook again once running vm task has finished.'
