
- name: 'ExaCS VM Cluster OCID'
  become: 'true'
  become_user: 'root'
  become_method: 'sudo'
  shell: |
    grep vmcluster_ocid= {{ exacs_props_path }}
  register: 'exacs_vm_cluster_ocid'
  delegate_to: '{{ hostgroup }}'
  
- debug: { msg: '{{ exacs_vm_cluster_ocid }}' }
- set_fact:
    vm_cluster_id: '{{ exacs_vm_cluster_ocid.stdout | regex_findall("vmcluster_ocid=(.+)") | first }}'

- name: ExaCS VM Cluster Discovery
  oci_database_cloud_vm_cluster_facts:
    cloud_vm_cluster_id: '{{ vm_cluster_id }}'
  register: vm_cluster_discovery_result
- debug: { msg: '{{ vm_cluster_discovery_result }}' }
- set_fact: 
    compartment_id: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].compartment_id }}'
    vm_cluster_lifecycle_state: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].lifecycle_state }}'
    vm_cluster_name: '{{ vm_cluster_discovery_result.cloud_vm_clusters[0].cluster_name }}'
  when: vm_cluster_discovery_result.cloud_vm_clusters|length == 1